### ISSUE TITLE
query with double quotes

### ISSUE THREAD

**Issue by marsiliflavio** [Daniel-SchaeferJ/Fluree.NET#15]
Hi,
have a problem
var query = new FlureeQueryBuilder
            {
                SqlSelect = new List<string>()
                {
                    "*",
                    "{\"chat\": [\"*\"]"
                },
                SqlFrom = "person"
            };
when JsonPostAsync chat return only chat/_id because the serialization Newtonsoft.Json.JsonConvert.SerializeObject(query)
"{\"select\":[\"*\",\"{\\\"chat\\\":[\\\"*\\\"]}\"],\"from\":\"person\"}"
and multiple quotes create a problem maybe

thanks
F.

**Comment by Daniel-SchaeferJ** [comment]
Hey @marsiliflavio! Thanks for bringing this to my attention. In the future I'll see if I can add a test with subsequent fix for your issue. In the meantime, if its returning a chat id, can you see if the entry you query has the same id? If it does might be a little more involved than that. You can do this with the fluree build in admin panel.

**Comment by marsiliflavio** [comment]
Yes, the query response only id for the chat.

**Comment by Daniel-SchaeferJ** [comment]
@marsiliflavio I tried to reproduce, but was unable too. All I can say is make sure to use the \" character, and if need be, don't pass in your object when calling ExecuteSingleQuery<YourObject>. What you can do instead is ExecuteSingleQuery<object> and deseralize it using library of choice. Let me know if any other questions!
